In [26]:
import pandas as pd

all_games = pd.read_csv('all_games_data.csv')

all_games.head()

,GAME_ID,TEAM_ID,TEAM_NAME,TEAM_ABBREVIATION,TEAM_CITY,MIN,FGM,FGA,FG_PCT,FG3M,...,AST_RATIO,OREB_PCT,DREB_PCT,REB_PCT,TM_TOV_PCT,EFG_PCT,TS_PCT,USG_PCT,PACE,PIE
0,0,1610612765,Pistons,DET,Detroit,240:00:00,37,96,0.385,12,...,15.8,0.411,0.837,0.596,15.084,0.448,0.493,0.200,98.02,0.538
1,0,1610612737,Hawks,ATL,Atlanta,240:00:00,37,82,0.451,8,...,17.5,0.163,0.589,0.404,15.528,0.500,0.530,0.200,98.02,0.462
2,1,1610612739,Cavaliers,CLE,Cleveland,240:00:00,38,94,0.404,9,...,18.8,0.216,0.848,0.515,10.840,0.452,0.468,0.198,102.30,0.521
3,1,1610612741,Bulls,CHI,Chicago,240:00:00,37,87,0.425,7,...,10.6,0.152,0.784,0.485,12.607,0.466,0.499,0.200,102.30,0.479
4,2,1610612740,Pelicans,NOP,New Orleans,240:00:00,35,83,0.422,6,...,15.6,0.186,0.543,0.371,17.945,0.458,0.501,0.198,105.28,0.375

In [27]:
all_games['TEAM_CITY'] = all_games['TEAM_CITY'].replace(['LA'], 'Los Angeles')

In [28]:
all_games['TEAM'] = all_games['TEAM_CITY']+' '+all_games['TEAM_NAME']
all_games['DATE'] = pd.to_datetime(all_games['DATE'])

In [29]:
ha = pd.read_csv('home_away.csv')

indices = [i for i in range(0,2460)]

ha['Date'] = pd.to_datetime(ha['Date'])
ha = ha.sort_values(['Date'], ascending = [True])
ha = ha.set_index([indices])

ha.to_csv('home_away.csv',index=False)

home = []
for row in all_games.iterrows():
    x = ha.loc[ha['Date'] == row[1]['DATE']]
    y = list(x['Visitor/Neutral'])
    if row[1]['TEAM'] in y:
        home.append(0)
    else:
        home.append(1)

all_games['HOME'] = home

all_games[0:10]

,GAME_ID,TEAM_ID,TEAM_NAME,TEAM_ABBREVIATION,TEAM_CITY,MIN,FGM,FGA,FG_PCT,FG3M,...,DREB_PCT,REB_PCT,TM_TOV_PCT,EFG_PCT,TS_PCT,USG_PCT,PACE,PIE,TEAM,HOME
0,0,1610612765,Pistons,DET,Detroit,240:00:00,37,96,0.385,12,...,0.837,0.596,15.084,0.448,0.493,0.200,98.02,0.538,Detroit Pistons,0
1,0,1610612737,Hawks,ATL,Atlanta,240:00:00,37,82,0.451,8,...,0.589,0.404,15.528,0.500,0.530,0.200,98.02,0.462,Atlanta Hawks,1
2,1,1610612739,Cavaliers,CLE,Cleveland,240:00:00,38,94,0.404,9,...,0.848,0.515,10.840,0.452,0.468,0.198,102.30,0.521,Cleveland Cavaliers,0
3,1,1610612741,Bulls,CHI,Chicago,240:00:00,37,87,0.425,7,...,0.784,0.485,12.607,0.466,0.499,0.200,102.30,0.479,Chicago Bulls,1
4,2,1610612740,Pelicans,NOP,New Orleans,240:00:00,35,83,0.422,6,...,0.543,0.371,17.945,0.458,0.501,0.198,105.28,0.375,New Orleans Pelicans,0
5,2,1610612744,Warriors,GSW,Golden State,240:00:00,41,96,0.427,9,...,0.814,0.629,19.106,0.474,0.525,0.200,105.28,0.625,Golden State Warriors,1
6,3,1610612764,Wizards,WAS,Washington,240:00:00,33,84,0.393,7,...,0.667,0.467,18.367,0.435,0.463,0.198,101.14,0.518,Washington Wizards,0
7,3,1610612753,Magic,ORL,Orlando,240:00:00,37,100,0.370,5,...,0.722,0.533,15.343,0.395,0.413,0.197,101.14,0.482,Orlando Magic,1
8,4,1610612738,Celtics,BOS,Boston,240:00:00,39,85,0.459,8,...,0.689,0.471,16.365,0.506,0.578,0.200,103.50,0.630,Boston Celtics,1
9,4,1610612755,76ers,PHI,Philadelphia,240:00:00,34,83,0.410,7,...,0.762,0.529,23.274,0.452,0.510,0.197,103.50,0.370,Philadelphia 76ers,0

In [30]:
import numpy as np

teams_dict = {key: value for key, value in all_games.groupby('TEAM_ABBREVIATION')}

teams_dict['LAC'][0:5]

,GAME_ID,TEAM_ID,TEAM_NAME,TEAM_ABBREVIATION,TEAM_CITY,MIN,FGM,FGA,FG_PCT,FG3M,...,DREB_PCT,REB_PCT,TM_TOV_PCT,EFG_PCT,TS_PCT,USG_PCT,PACE,PIE,TEAM,HOME
30,15,1610612746,Clippers,LAC,Los Angeles,240:00:00,42,80,0.525,6,...,0.750,0.462,14.614,0.563,0.593,0.200,105.28,0.571,Los Angeles Clippers,0
38,19,1610612746,Clippers,LAC,Los Angeles,240:00:00,38,87,0.437,8,...,0.763,0.491,7.880,0.483,0.512,0.200,102.06,0.622,Los Angeles Clippers,1
75,37,1610612746,Clippers,LAC,Los Angeles,240:00:00,39,76,0.513,4,...,0.648,0.456,15.852,0.539,0.592,0.200,107.12,0.597,Los Angeles Clippers,1
102,51,1610612746,Clippers,LAC,Los Angeles,240:00:00,37,81,0.457,8,...,0.729,0.455,11.098,0.506,0.560,0.200,100.18,0.559,Los Angeles Clippers,1
136,68,1610612746,Clippers,LAC,Los Angeles,240:00:00,43,88,0.489,8,...,0.775,0.494,12.912,0.534,0.553,0.196,101.16,0.459,Los Angeles Clippers,0

In [31]:
indices = [i for i in range(0,164)]

for key in teams_dict:
    teams_dict[key] = teams_dict[key].set_index([indices])
    
teams_dict['GSW'][0:21]

,GAME_ID,TEAM_ID,TEAM_NAME,TEAM_ABBREVIATION,TEAM_CITY,MIN,FGM,FGA,FG_PCT,FG3M,...,DREB_PCT,REB_PCT,TM_TOV_PCT,EFG_PCT,TS_PCT,USG_PCT,PACE,PIE,TEAM,HOME
0,2,1610612744,Warriors,GSW,Golden State,240:00:00,41,96,0.427,9,...,0.814,0.629,19.106,0.474,0.525,0.200,105.28,0.625,Golden State Warriors,1
1,29,1610612744,Warriors,GSW,Golden State,240:00:00,43,93,0.462,9,...,0.750,0.490,7.921,0.511,0.538,0.200,101.92,0.613,Golden State Warriors,0
2,34,1610612744,Warriors,GSW,Golden State,240:00:00,46,84,0.548,17,...,0.686,0.442,9.398,0.649,0.674,0.200,108.26,0.579,Golden State Warriors,0
3,50,1610612744,Warriors,GSW,Golden State,240:00:00,43,84,0.512,11,...,0.833,0.596,13.834,0.577,0.612,0.200,103.50,0.840,Golden State Warriors,1
4,68,1610612744,Warriors,GSW,Golden State,240:00:00,39,85,0.459,10,...,0.767,0.506,11.806,0.518,0.568,0.200,101.16,0.541,Golden State Warriors,1
5,82,1610612744,Warriors,GSW,Golden State,240:00:00,46,93,0.495,17,...,0.800,0.546,18.532,0.586,0.590,0.200,109.30,0.587,Golden State Warriors,1
6,91,1610612744,Warriors,GSW,Golden State,240:00:00,38,92,0.413,8,...,0.705,0.505,17.195,0.457,0.506,0.200,103.86,0.552,Golden State Warriors,0
7,103,1610612744,Warriors,GSW,Golden State,240:00:00,43,91,0.473,12,...,0.700,0.500,16.045,0.538,0.563,0.200,99.66,0.595,Golden State Warriors,1
8,119,1610612744,Warriors,GSW,Golden State,240:00:00,36,75,0.480,11,...,0.744,0.468,22.745,0.553,0.587,0.200,98.98,0.566,Golden State Warriors,0
9,124,1610612744,Warriors,GSW,Golden State,240:00:00,48,89,0.539,18,...,0.643,0.413,10.887,0.640,0.672,0.200,100.94,0.566,Golden State Warriors,0
10,143,1610612744,Warriors,GSW,Golden State,265:00:00,43,97,0.443,12,...,0.780,0.500,14.231,0.505,0.528,0.198,96.20,0.530,Golden State Warriors,1
11,163,1610612744,Warriors,GSW,Golden State,240:00:00,43,80,0.537,11,...,0.676,0.459,19.440,0.606,0.626,0.200,103.52,0.545,Golden State Warriors,1
12,176,1610612744,Warriors,GSW,Golden State,240:00:00,38,73,0.521,17,...,0.800,0.557,19.030,0.637,0.698,0.200,100.20,0.569,Golden State Warriors,0
13,186,1610612744,Warriors,GSW,Golden State,240:00:00,39,79,0.494,10,...,0.717,0.533,16.920,0.557,0.592,0.198,94.84,0.582,Golden State Warriors,1
14,199,1610612744,Warriors,GSW,Golden State,240:00:00,47,89,0.528,15,...,0.729,0.529,20.053,0.612,0.623,0.200,106.56,0.598,Golden State Warriors,0
15,213,1610612744,Warriors,GSW,Golden State,240:00:00,45,92,0.489,12,...,0.818,0.516,8.457,0.554,0.563,0.200,95.82,0.683,Golden State Warriors,1
16,235,1610612744,Warriors,GSW,Golden State,240:00:00,46,81,0.568,22,...,0.857,0.639,22.297,0.704,0.713,0.198,108.38,0.611,Golden State Warriors,0
17,244,1610612744,Warriors,GSW,Golden State,240:00:00,39,80,0.487,16,...,0.648,0.500,16.556,0.588,0.641,0.196,99.62,0.633,Golden State Warriors,1
18,258,1610612744,Warriors,GSW,Golden State,240:00:00,40,82,0.488,14,...,0.756,0.563,16.741,0.573,0.598,0.200,93.64,0.525,Golden State Warriors,0
19,267,1610612744,Warriors,GSW,Golden State,240:00:00,46,88,0.523,16,...,0.764,0.564,20.420,0.614,0.625,0.195,102.52,0.596,Golden State Warriors,0
20,289,1610612744,Warriors,GSW,Golden State,240:00:00,35,73,0.479,16,...,0.761,0.531,12.925,0.589,0.630,0.200,95.14,0.527,Golden State Warriors,0

In [32]:
#cols = [col for col in all_games.columns if col not in ['GAME_ID', 'OFFICIAL_GAME_ID','TEAM_ID','TEAM_NAME','TEAM_ABBREVIATION','TEAM_CITY','MIN','DATE']]
columns = []
for col in all_games.columns:
    if col not in ['GAME_ID', 'OFFICIAL_GAME_ID','TEAM_ID','TEAM','TEAM_NAME','TEAM_ABBREVIATION','TEAM_CITY','MIN','DATE']:
        columns.append(col+'_0')
        columns.append(col+'_1')
        
columns.append('WIN_PCT_0')
columns.append('WIN_PCT_1')
columns.append('WINNER')

In [33]:
teams = {}
count = 0
num = 15

for row in all_games.iterrows():
    if row[1]['TEAM_ABBREVIATION'] in teams:
        teams[row[1]['TEAM_ABBREVIATION']] += 1
    else:
        teams[row[1]['TEAM_ABBREVIATION']] = 1
        
    if all(value >= num for value in teams.values()):
        break
    count+=1
    
count

522

In [34]:
games = []
game = pd.DataFrame(columns = columns)

zero_one = 0
winner = -1
for row in all_games[count+2:].iterrows():    
    idx = teams_dict[row[1]['TEAM_ABBREVIATION']].index[teams_dict[row[1]['TEAM_ABBREVIATION']]['GAME_ID'] == row[1]['GAME_ID']]
    idx = idx.tolist()[0]
    last_ten = teams_dict[row[1]['TEAM_ABBREVIATION']][idx-num:idx]
    current_game = teams_dict[row[1]['TEAM_ABBREVIATION']][idx:idx+1]

    if zero_one == 0:
        #print(row[1]['GAME_ID'])
        #print(row[1]['DATE'])
        #print(row[1]['TEAM_ABBREVIATION'])
        
        for i in range(0,len(columns),2):
            if columns[i] not in ['WINNER','WIN_PCT_0']:
                game.at[0,columns[i]] = last_ten[columns[i][:-2]].mean()
                
        game.at[0,'HOME_0'] = current_game['HOME'].values[0]
        game.at[0,'WIN_PCT_0'] = len(last_ten[last_ten['PLUS_MINUS'] > 0]) / len(last_ten)
        
        winner = row[1]['PLUS_MINUS']
        #print(winner)
        if winner > 0:
            game.at[0,'WINNER'] = 0
        else:
            game.at[0,'WINNER'] = 1
        
        zero_one = 1
        
    else:
        #print(row[1]['GAME_ID'])
        #print(row[1]['TEAM_ABBREVIATION'])
        for i in range(1,len(columns),2):
            if columns[i] not in ['WINNER','WIN_PCT_1']:
                game.at[0,columns[i]] = last_ten[columns[i][:-2]].mean()
    
        game.at[0,'HOME_1'] = current_game['HOME'].values[0]
        game.at[0,'WIN_PCT_1'] = len(last_ten[last_ten['PLUS_MINUS']> 0]) / len(last_ten)
        
        games.append(game)
        game = pd.DataFrame(columns = columns)
        zero_one = 0
        winner = -1

In [35]:
indices = [i for i in range(0,len(games))]
feature_vector = pd.concat(games)
feature_vector = feature_vector.set_index([indices])

filepath = 'feature_vectors.csv'
feature_vector.to_csv(filepath)

feature_vector.head()

,FGM_0,FGM_1,FGA_0,FGA_1,FG_PCT_0,FG_PCT_1,FG3M_0,FG3M_1,FG3A_0,FG3A_1,...,USG_PCT_1,PACE_0,PACE_1,PIE_0,PIE_1,HOME_0,HOME_1,WIN_PCT_0,WIN_PCT_1,WINNER
0,34.6,34.2667,83.8,81.9333,0.415067,0.419733,8,8.66667,24.9333,27.3333,...,0.198,99.208,100.24,0.441733,0.4194,0,1,0.133333,0,1
1,38.4,39.7333,86.6667,88.4,0.4436,0.451533,5.06667,11,16.5333,26.8667,...,0.198733,98.6413,102.259,0.4762,0.499333,1,0,0.266667,0.466667,0
2,38.4667,37.3333,87.7333,83.3333,0.439867,0.4498,8.46667,5.66667,23.1333,16.4,...,0.198933,97.902,98.8367,0.501533,0.503867,0,1,0.6,0.4,0
3,38.1333,34.5333,85.5333,81.6,0.446267,0.426533,8.93333,5.73333,25.8667,18.0667,...,0.198667,100.095,97.7893,0.46,0.479,1,0,0.266667,0.533333,1
4,36.1333,37.2667,81.4667,83.9333,0.444133,0.4462,7.86667,8.73333,25.6667,25.2,...,0.199133,99.028,97.0707,0.5152,0.478533,0,1,0.533333,0.4,0